package dev.jevoas.sentinel.report;

import dev.jevoas.sentinel.json.Json;
import dev.jevoas.sentinel.openapi.Severity;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

public final class ReportRenderer {
    public String render(Report report, String format) {
        return switch (format.toLowerCase(Locale.ROOT)) {
            case "json" -> Json.writePretty(toMap(report));
            case "markdown", "md" -> markdown(report);
            case "sarif" -> Json.writePretty(sarif(report));
            default -> throw new IllegalArgumentException("Unsupported format: " + format);
        };
    }

    private Map<String, Object> toMap(Report report) {
        LinkedHashMap<String, Object> result = new LinkedHashMap<>();
        result.put("tool", Map.of("name", "jev-oas-sentinel", "version", report.toolVersion()));
        result.put("generated_at", report.generatedAt().toString());
        result.put("base", report.base());
        result.put("head", report.head());
        result.put("mode", report.mode());
        result.put("requested_model", report.requestedModel());
        result.put("summary", Map.of(
                "blocks", report.count(Severity.BLOCK),
                "reviews", report.count(Severity.REVIEW),
                "notices", report.count(Severity.NOTICE)));
        result.put("metrics", report.metrics());
        result.put("findings", report.findings().stream().map(this::findingMap).toList());
        return result;
    }

    private Map<String, Object> findingMap(Finding finding) {
        LinkedHashMap<String, Object> result = new LinkedHashMap<>();
        result.put("rule_id", finding.ruleId());
        result.put("severity", finding.severity().name().toLowerCase(Locale.ROOT));
        result.put("operation", finding.operation());
        result.put("message", finding.message());
        result.put("source", finding.source());
        result.put("evidence", finding.evidence());
        return result;
    }

    private String markdown(Report report) {
        StringBuilder output = new StringBuilder();
        output.append("# JEV OpenAPI Sentinel\n\n");
        output.append("Compared `").append(escapeMarkdown(report.base())).append("` → `")
                .append(escapeMarkdown(report.head())).append("` in **")
                .append(report.mode()).append("** mode.\n\n");
        output.append("| Block | Review | Notice |\n");
        output.append("|---:|---:|---:|\n");
        output.append('|').append(report.count(Severity.BLOCK))
                .append('|').append(report.count(Severity.REVIEW))
                .append('|').append(report.count(Severity.NOTICE)).append("|\n\n");

        if (report.findings().isEmpty()) {
            output.append("No changes requiring a finding were detected.\n");
            return output.toString();
        }

        output.append("| Severity | Operation | Rule | Finding |\n");
        output.append("|---|---|---|---|\n");
        for (Finding finding : report.findings()) {
            output.append('|').append(icon(finding.severity())).append(' ')
                    .append(finding.severity().name().toLowerCase(Locale.ROOT)).append('|')
                    .append('`').append(escapeMarkdown(finding.operation())).append('`').append('|')
                    .append('`').append(escapeMarkdown(finding.ruleId())).append('`').append('|')
                    .append(escapeMarkdown(finding.message())).append("|\n");
        }
        output.append("\nGenerated by jev-oas-sentinel ").append(report.toolVersion()).append(".\n");
        return output.toString();
    }

    private Map<String, Object> sarif(Report report) {
        List<Map<String, Object>> rules = report.findings().stream()
                .map(Finding::ruleId)
                .distinct()
                .map(rule -> Map.<String, Object>of(
                        "id", rule,
                        "name", rule,
                        "shortDescription", Map.of("text", humanize(rule))))
                .toList();
        List<Map<String, Object>> results = new ArrayList<>();
        for (Finding finding : report.findings()) {
            LinkedHashMap<String, Object> result = new LinkedHashMap<>();
            result.put("ruleId", finding.ruleId());
            result.put("level", sarifLevel(finding.severity()));
            result.put("message", Map.of("text", finding.operation() + ": " + finding.message()));
            result.put("locations", List.of(Map.of(
                    "physicalLocation", Map.of(
                            "artifactLocation", Map.of("uri", finding.source())))));
            result.put("properties", Map.of(
                    "operation", finding.operation(),
                    "sentinelSeverity", finding.severity().name().toLowerCase(Locale.ROOT),
                    "evidence", finding.evidence()));
            results.add(result);
        }

        Map<String, Object> driver = Map.of(
                "name", "jev-oas-sentinel",
                "version", report.toolVersion(),
                "informationUri", "https://docs.typesafe.ai/introduction",
                "rules", rules);
        Map<String, Object> run = Map.of(
                "tool", Map.of("driver", driver),
                "results", results,
                "properties", Map.of(
                        "base", report.base(),
                        "head", report.head(),
                        "mode", report.mode(),
                        "metrics", report.metrics()));
        LinkedHashMap<String, Object> sarif = new LinkedHashMap<>();
        sarif.put("$schema", "https://json.schemastore.org/sarif-2.1.0.json");
        sarif.put("version", "2.1.0");
        sarif.put("runs", List.of(run));
        return sarif;
    }

    private String sarifLevel(Severity severity) {
        return switch (severity) {
            case BLOCK -> "error";
            case REVIEW -> "warning";
            case NOTICE -> "note";
        };
    }

    private String icon(Severity severity) {
        return switch (severity) {
            case BLOCK -> "🛑";
            case REVIEW -> "⚠️";
            case NOTICE -> "ℹ️";
        };
    }

    private String humanize(String rule) {
        String normalized = rule.replace('-', ' ');
        return Character.toUpperCase(normalized.charAt(0)) + normalized.substring(1);
    }

    private String escapeMarkdown(String value) {
        return value.replace("|", "\\|").replace("`", "\\`").replace("\n", " ");
    }
}

