from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import json
from typing import Any

from .policy import Finding


@dataclass(frozen=True)
class Report:
    version: str
    generated_at: datetime
    base: str
    head: str
    mode: str
    requested_model: str
    findings: tuple[Finding, ...]
    metrics: dict[str, Any]

    def count(self, severity: str) -> int:
        return sum(finding.severity == severity for finding in self.findings)

    @property
    def has_blocks(self) -> bool:
        return self.count("block") > 0

    @property
    def has_reviews(self) -> bool:
        return self.count("review") > 0


def render(report: Report, output_format: str) -> str:
    normalized = output_format.lower()
    if normalized == "json":
        return json.dumps(_mapping(report), indent=2, ensure_ascii=False) + "\n"
    if normalized in {"markdown", "md"}:
        return _markdown(report)
    if normalized == "sarif":
        return json.dumps(_sarif(report), indent=2, ensure_ascii=False) + "\n"
    raise ValueError(f"Unsupported format: {output_format}")


def _mapping(report: Report) -> dict[str, Any]:
    return {
        "tool": {"name": "jev-oas-sentinel", "version": report.version},
        "generated_at": report.generated_at.isoformat().replace("+00:00", "Z"),
        "base": report.base,
        "head": report.head,
        "mode": report.mode,
        "requested_model": report.requested_model,
        "summary": {
            "blocks": report.count("block"),
            "reviews": report.count("review"),
            "notices": report.count("notice"),
        },
        "metrics": report.metrics,
        "findings": [finding.to_dict() for finding in report.findings],
    }


def _markdown(report: Report) -> str:
    output = [
        "# JEV OpenAPI Sentinel",
        "",
        f"Compared `{_escape(report.base)}` → `{_escape(report.head)}` in **{report.mode}** mode.",
        "",
        "| Block | Review | Notice |",
        "|---:|---:|---:|",
        f"|{report.count('block')}|{report.count('review')}|{report.count('notice')}|",
        "",
    ]
    if not report.findings:
        output.append("No changes requiring a finding were detected.")
    else:
        output.extend(["| Severity | Operation | Rule | Finding |", "|---|---|---|---|"])
        icons = {"block": "🛑", "review": "⚠️", "notice": "ℹ️"}
        output.extend(
            f"|{icons[finding.severity]} {finding.severity}|`{_escape(finding.operation)}`|"
            f"`{_escape(finding.rule_id)}`|{_escape(finding.message)}|"
            for finding in report.findings
        )
        output.extend(["", f"Generated by jev-oas-sentinel {report.version}."])
    return "\n".join(output) + "\n"


def _sarif(report: Report) -> dict[str, Any]:
    rule_ids = list(dict.fromkeys(finding.rule_id for finding in report.findings))
    rules = [{
        "id": rule_id,
        "name": rule_id,
        "shortDescription": {"text": rule_id.replace("-", " ").capitalize()},
    } for rule_id in rule_ids]
    levels = {"block": "error", "review": "warning", "notice": "note"}
    results = [{
        "ruleId": finding.rule_id,
        "level": levels[finding.severity],
        "message": {"text": f"{finding.operation}: {finding.message}"},
        "locations": [{"physicalLocation": {"artifactLocation": {"uri": finding.source}}}],
        "properties": {
            "operation": finding.operation,
            "sentinelSeverity": finding.severity,
            "evidence": finding.evidence,
        },
    } for finding in report.findings]
    return {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [{
            "tool": {"driver": {
                "name": "jev-oas-sentinel",
                "version": report.version,
                "informationUri": "https://docs.typesafe.ai/introduction",
                "rules": rules,
            }},
            "results": results,
            "properties": {
                "base": report.base,
                "head": report.head,
                "mode": report.mode,
                "metrics": report.metrics,
            },
        }],
    }


def _escape(value: str) -> str:
    return value.replace("|", "\\|").replace("`", "\\`").replace("\n", " ")

